from big_ol_pile_of_manim_imports import *

class ShapeTransformations(Scene):
    def construct(self):
        #define shapes
        c = Circle()
        s = Square()
        r3 = RegularPolygon(n = 3)
        r6 = RegularPolygon(n = 6)
        r8 = RegularPolygon(n = 8)
        #define textmobject and position
        oText = TextMobject("manimProjects - github.com/sujay-mahadik")
        t1 = TextMobject("Shape Transformations")
        sText = TextMobject("Square")
        sText.set_color(BLUE)
        sText.shift(2 * UP)
        cText = TextMobject("Circle")
        cText.set_color(PINK)
        cText.shift(2 * UP)
        r3Text = TextMobject("Regular Polygon with 3 sides")
        r3Text.set_color(GREEN)
        r3Text.shift(2 * UP)
        r6Text = TextMobject("Regular Polygon with 6 sides")
        r6Text.set_color(RED)
        r6Text.shift(2 * UP)
        r8Text = TextMobject("Regular Polygon with 8 sides")
        r8Text.set_color(YELLOW)
        r8Text.shift(2 * UP)
        #set color and fill color for shapes
        s.set_fill(BLUE, opacity=0.5)
        s.set_color(BLUE)
        c.set_fill(PINK, opacity=0.5)
        c.set_color(PINK)
        r3.set_fill(GREEN, opacity=0.5)
        r3.set_color(GREEN)
        r6.set_fill(RED, opacity=0.5)
        r6.set_color(RED)
        r8.set_fill(YELLOW, opacity=0.5)
        r8.set_color(YELLOW)

        self.play(ShowCreation(oText))
        self.wait(1)
        self.play(Transform(oText, t1))
        self.wait(1)
        self.play(ApplyMethod(oText.shift, 2 * UP))
        self.play(Transform(oText, sText), ShowCreation(s))
        self.wait(2)
        self.play(Transform(oText, cText), Transform(s, c))
        self.wait(2)
        self.play(Transform(oText, r3Text), Transform(s, r3))
        self.wait(2)
        self.play(Transform(oText, r6Text), Transform(s, r6))
        self.wait(2)
        self.play(Transform(oText, r8Text), Transform(s, r8))
        self.wait(4)
